name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Install Dependencies and Build
        run: |
          pnpm install
          npm run build

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.PHIMHAY247_PK }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: ssh-keyscan -t rsa ${{ secrets.PHIMHAY247_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -r --update --delete-after ./.output/public ${{ secrets.PHIMHAY247_USERNAME }}@${{ secrets.PHIMHAY247_IP }}:/home/phimhay247z/htdocs/phimhay247z.org

          rsync -r --update --delete-after ./.output/server ${{ secrets.PHIMHAY247_USERNAME }}@${{ secrets.PHIMHAY247_IP }}:/home/phimhay247z/htdocs/phimhay247z.org

          rsync -r --update --delete-after ./ecosystem.config.cjs ${{ secrets.PHIMHAY247_USERNAME }}@${{ secrets.PHIMHAY247_IP }}:/home/phimhay247z/htdocs/phimhay247z.org

      - name: Start app on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PHIMHAY247_IP }}
          username: ${{ secrets.PHIMHAY247_USERNAME }}
          key: ${{ secrets.PHIMHAY247_PK }}
          script: |
            cd /home/phimhay247z/htdocs/phimhay247z.org
            /home/azure/.nvm/versions/node/v19.9.0/bin/pm2 reload ecosystem.config.cjs
